### ISSUE TITLE
Update included Syncthing

### ISSUE THREAD

**Issue by runical** [fuchsmich/syncthing-sf#1]
Hey fuchsmich, syncthing version 0.13.1 was released a few days back and it would be great if you could update the included syncthing as the 0.12.x versions cannot talk to the 0.13.x versions.

**Comment by fuchsmich** [comment]
I uploaded an update on openrepos.

**Comment by runical** [comment]
Thank you. I installed it just now and it seems to work just fine. Are you still working on a mechanism to check for updates and just update syncthing in place instead of having to update it like this?

**Comment by fuchsmich** [comment]
Yes. The idea is to copy the binary file (with QFile) to a location in the home path, so it is writeable for the user nemo. Then of course the systemd service unit file has to be update. This could be done be reading/creating the file with QSettings in c++.

**Comment by runical** [comment]
Why would you need to recreate the file? Just copy it over and run `systemctl --user deamon-reload` and `systemctl --user restart syncthing`. If you want to make changes to the file, you should use an override file.
