### ISSUE TITLE
Return the official name stylization

### ISSUE THREAD

**Issue by mirceasava** [fuchsmich/syncthing-sf#2]
Could you rename it Syncthing in the .desktop file instead of SyncThing and remove the GUI part from the name?
It's common sense that if there's an icon present it's most likely a GUI.

**Comment by fuchsmich** [comment]
Thanks for your comment.
This is not maintained anymore.
Here is the successor: https://openrepos.net/content/fooxl/syncdings
Apperently I forgot to upload the source here. Will do this soon.

**Comment by fuchsmich** [comment]
I uploaded the sources for Syncdings now: 
https://github.com/fuchsmich/syncdings
